package com.github.mariyamango.tb.javarushclient.dto;

/**
 * Group Visibility status.
 */

public enum GroupLanguage {
    UNKNOWN, ENGLISH, GERMAN, SPANISH, HINDI, FRENCH, PORTUGUESE, POLISH, BENGALI, PUNJABI, CHINESE, ITALIAN,
    INDONESIAN, MARATHI, TAMIL, TELUGU, JAPANESE, KOREAN, URDU, TAIWANESE, NETHERLANDS,
    RUSSIAN, UKRAINIAN, BULGARIAN, DANISH, HUNGARIAN, JAVANESE, MALAY, NORWEGIAN, ROMANIAN, SWEDISH, THAI, FILIPINO,
    TURKISH, VIETNAMESE, ARABIC, PERSIAN, HEBREW, SINDHI, AZERBAIJANI, KAZAKH, KYRGYZ, TAJIK, TURKMEN, UZBEK
}